Techno.ASP/Models/Forms/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Techno.ASP.Models.Forms
{
    public class ContactForm
    {
        [Required]
        [EmailAddress]
        [MaxLength(200)]
        [Display(Name = "Votre adresse email (*)")]
        
        public string Email { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(1000)]
        [Display(Name = "Votre message (*)")]
        public string Message { get; set; }
    }
}

Techno.ASP/Areas/Member/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Techno.ASP.Models;
using Techno.ASP.Tools;

namespace Techno.ASP.Areas.Member.Controllers
{
    [Area("Member")] //OBLIGATOIRE
    [Authorize(Policy = "RoleStudentPolicy")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        { 
                UserModel um = SessionUtils.ConnectedUser;
                TempData["success"] = $"Bienvenue {um.FirstName}";
                return View();
             
        }

        public IActionResult Logout()
        {
            //Processus de Logout
            HttpContext.Session.Clear();
            //Redirection vers la page principale du site
            return RedirectToAction("Index", "Home", new { area = "" });

        }

    }
}

Techno.ASP/Controllers/HomeController.cs
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MimeKit;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Techno.ASP.Models;
using Techno.ASP.Models.Forms;
using Techno.ASP.Services;
using Techno.ASP.Tools;
namespace Techno.ASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly Mailer _mailer;

        // injection de dépendances par constructeur
        public HomeController(ILogger<HomeController> logger, Mailer mailer)
        {
            _logger = logger;
            _mailer = mailer;
        }

        public IActionResult Index()
        {

            TempData["isLogged"] = HttpContext.Session.Get<bool>("IsLogged");
           
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult AboutMe()
        {
            AboutMeModel model = new AboutMeModel
            {
                Nom = "Ly",
                Prenom = "Khun",
                DateDeNaissance = new DateTime(1982,5,6)
            };

            return View(model);
        }

        // afficher le formulaire
        public IActionResult Contact()
        {
            return View();
        }

        // traiter le formulaire
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Contact([FromForm]ContactForm form)
        {
            // verifier si le formulaire est valide
            // si oui on envoie un email + redirection
            if(ModelState.IsValid)
            {
                // envoyer un email
                string sub = "Vous avez recu un message de la part de " + form.Email;
                string content = $"<p>{form.Message}</p>";
                bool result = _mailer.Send("lykhun@gmail.com", sub, content);
                if(result)
                {
                    // notification success
                    TempData["success"] = "Votre message a bien été envoyé";
                }
                else
                {
                    // notification erreur
                    TempData["error"] = "Une erreur est survenue";
                }
                ViewBag.Info = "copperfield";
                // rediriger
                return RedirectToAction("Index");
            }
            // si non on reste sur la page et on affiche les erreurs 
            else
            {
                
                return View(form);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Techno.ASP/ViewComponents/MeteoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Techno.ASP.Models;

namespace Techno.ASP.ViewComponents
{
    public class MeteoViewComponent : ViewComponent
    {
        private readonly string url = "https://api.openweathermap.org/data/2.5/weather";

        private readonly IConfiguration _config;
        private readonly HttpClient _client;

        public MeteoViewComponent(IConfiguration config, HttpClient client)
        {
            _config = config;
            _client = client;
        }

        public IViewComponentResult Invoke()
        {
            HttpResponseMessage message = _client.GetAsync(
                url + "?q=charleroi&APPID=" + _config.GetSection("ApiKeys").GetValue<string>("OPWM") + "&units=metric"
            ).Result;
            string json = message.Content.ReadAsStringAsync().Result;
            MeteoModel model = JsonConvert.DeserializeObject<MeteoModel>(json);
            return View(model);
        }
    }
}

Techno.ASP/Views/Home/AboutMe.cshtml
@model AboutMeModel
@{
    ViewData["Title"] = "A propos de moi";
}

<p>@Model.Nom</p>
<p>@Model.Prenom</p>
<p>@Model.DateDeNaissance.ToShortDateString()</p>

<vc:meteo></vc:meteo>

Techno.ASP/Views/Home/Contact.cshtml
@model Techno.ASP.Models.Forms.ContactForm

@{
    ViewData["Title"] = "Contact";
}

<link rel="stylesheet" href="~/css/contact.css"/>

<h1>Contact</h1>

<h4>ContactForm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input class="form-control" type="email" data-val="true" data-val-email="The Votre adresse email (*) field is not a valid e-mail address." data-val-maxlength="The field Votre adresse email (*) must be a string or array type with a maximum length of &#x27;200&#x27;." data-val-maxlength-max="200" data-val-required="The Votre adresse email (*) field is required." id="Email" maxlength="200" name="Email" value="" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <textarea asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <input type="submit" value="Envoyer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Techno.ASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>