Techno.ASP/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Techno.ASP.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Techno.ASP/Controllers/SectionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Techno.ASP.Models;
using Techno.ASP.Models.Forms;
using Techno.ASP.Services;

namespace Techno.ASP.Controllers
{
    public class SectionController : Controller
    {
        private readonly IService<SectionModel,SectionForm> _service;

        public SectionController(IService<SectionModel, SectionForm> service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            IEnumerable<SectionModel> model = _service.GetAll();
            return View(model);
        }

        //affichage
        public IActionResult Create()
        {
            return View();
        }

        //retour traitement
        [HttpPost]
        public IActionResult Create(SectionForm form)
        {
            // correct?
            // si oui
            if (ModelState.IsValid)
            {
                // service pour inserer
                _service.Insert(form);
                // Notification
                TempData["success"] = "Insertion OK";
                // redirection
                return RedirectToAction("Index");
            }
            else
            {
                // si non
                // réafficher la vue avec le form et les erreurs
                return View(form);
            }
        }

        // affichage
        public IActionResult Update([FromRoute] int id)
        {
            SectionForm form = _service.GetById(id);
            if (form == null) return NotFound();
            return View(form);
        }
        //traitement
        [HttpPost]
        public IActionResult Update(SectionForm form)
        {
            if (ModelState.IsValid)
            {
                _service.Update(form);
                TempData["success"] = "Modification OK";
                return RedirectToAction("Index");
            }
            else
            {
                return View(form);
            }
        }

        public IActionResult Delete([FromRoute] int id)
        {
            if (_service.Delete(id))
            {
                TempData["success"] = "Suppression OK";
            }
            else
            {
                TempData["error"] = "Ca n'a pas fonctionné";
            }
            return RedirectToAction("Index");
        }
    }
}

Techno.ASP/Controllers/SkillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Techno.ASP.Infra;
using Techno.ASP.Models;
using Techno.ASP.Models.Forms;
using Techno.ASP.Services;

namespace Techno.ASP.Controllers
{
    [Authorize(Policy = "RoleAdminPolicy")]
    public class SkillController : Controller
    {
        private readonly IService<SkillModel, SkillForm> _service;

        public SkillController(IService<SkillModel,SkillForm> service)
        {
            _service = service;
        }
        
        public IActionResult Index()
        {
            IEnumerable<SkillModel> model = _service.GetAll();
            return View(model);
        }

        //affichage
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //retour traitement
        [HttpPost]
        public IActionResult Create(SkillForm form)
        {
            // correct?
            // si oui
            if(ModelState.IsValid) {
                // service pour inserer
                _service.Insert(form);
                // Notification
                TempData["success"] = "Insertion OK";
                // redirection
                return RedirectToAction("Index");
            }
            else
            {
                // si non
                // réafficher la vue avec le form et les erreurs
                return View(form);
            }
        }

        // affichage
        public IActionResult Update([FromRoute]int id)
        {
            SkillForm form = _service.GetById(id);
            if (form == null) return NotFound();
            return View(form);
        }
        //traitement
        [HttpPost]
        public IActionResult Update(SkillForm form)
        {
            if(ModelState.IsValid)
            {
                _service.Update(form);
                TempData["success"] = "Modification OK";
                return RedirectToAction("Index");
            }
            else
            {
                return View(form);
            }
        }

        public IActionResult Delete([FromRoute]int id)
        {
            if(_service.Delete(id))
            {
                TempData["success"] = "Suppression OK";
            }
            else 
            {
                TempData["error"] = "Ca n'a pas fonctionné";
            }
            return RedirectToAction("Index");
        }
    }
}

Techno.ASP/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Techno.ASP.Models;
using Techno.ASP.Models.Forms;
using Techno.ASP.Services;
using Techno.ASP.Tools;
namespace Techno.ASP.Controllers
{
    public class UserController : Controller
    {
        IService<UserModel, RegisterUserForm> _service;
        public UserController(IService<UserModel,RegisterUserForm> service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(RegisterUserForm form)
        {
            if(ModelState.IsValid)
            {
                _service.Insert(form);
                TempData["success"] = "Formulaire ok";
                HttpContext.Session.Set<bool>("IsLogged", true);
                //Je redirige vers la création de profile
                return RedirectToAction("Create", "Profile",new { id = form.Id }); //L'id
            }
            else
            {
                TempData["error"] = "Formulaire invalide";
                return View(form);
            }
        }
    }
}

Techno.ASP/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Techno.ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/admin.css" />
</head>
<body>
    <header>
        <div class="buttons">
            <i id="menu-button" class="fa fa-bars clickable"></i>
        </div>
        <h1>
            Admin
        </h1>
        <div class="buttons">
            <a><i class="fa fa-power-off"></i></a>
        </div>
    </header>
    <div id="content" class="d-flex">
        <aside id="menu">
            <nav>
                <ul>
                    <li><a asp-action="Index"  asp-area="" asp-controller="Home">Home page</a></li>
                    <li><a asp-controller="Section" asp-action="Index"><i class="menu-icon fa fa-star"></i> Sections</a></li>
                    <li><a asp-controller="Skill" asp-action="Index"><i class="menu-icon fa fa-book"></i> Skills</a></li>
                </ul>
            </nav>
        </aside>
        <main role="main" class="pb-3 container-fluid">
            @RenderBody()
        </main>
    </div>
    <footer>
        &copy; 2021 - TechnofuturTIC
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/admin.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @if (TempData["success"] != null)
    {
        // toast vert
        <script>
            toastr.success('@TempData["success"]');
        </script>
    }
    else if (TempData["error"] != null)
    {
        // toast rouge
        <script>
             toastr.error('@TempData["error"]');
        </script>
    }
</body>
</html>

Techno.ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Techno.ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <partial name="_menu" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["success"] != null)
            {
                // message vert
                <div class="alert alert-success">
                    <p>@TempData["success"]</p>
                </div>
            }
            else if (TempData["error"] != null)
            {
                // message rouge
                <div class="alert alert-danger">
                    <p>@TempData["error"]</p>
                </div>
            }
            @RenderBody()
        </main>
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TechnofuturTIC - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @if (TempData["success"] != null)
    {
        // toast vert
        <script>
            toastr.success('@TempData["success"]');
        </script>
    }
    else if (TempData["error"] != null)
    {
        // toast rouge
        <script>
             toastr.error('@TempData["error"]');
        </script>
    }
</body>
</html>

Techno.ASP/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Techno.ASP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Demo" asp-action="Index">Demo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home" asp-action="AboutMe">A propos de moi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Contact">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Skill" asp-action="Index">Admin</a>
                </li>
                @if (!SessionUtils.IsLogged)
                {
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="User" asp-action="Create">Enregistrez-vous</a>
                </li>
                }
                else
                {
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Security" asp-action="Login" >Connectez-vous</a>
                </li>
                }
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index" asp-area="Member">Zone Membre</a>
                </li>
            </ul>
        </div>
    </div>
</nav>